name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Haskell Setup
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.2.5'
          cabal-version: '3.6.2.0'
          
      - name: Repo Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        run: make tests

      - name: Update Badges
        run: |
          test_types=("err" "fun" "opt")

          for test_type in "${test_types[@]}"; do
            percentage=$(grep -Po "(?<=PERC_${test_type}_PASSED=)(100|[0-9]{1,2})" 'tests_outputs/.log')

            if (( $(echo "$percentage < 50" | bc -l) )); then
              color="red"
            elif (( $(echo "$percentage < 80" | bc -l) )); then
              color="yellow"
            else
              color="brightgreen"
            fi

            label="Test_${test_type}"
            badge_url="https://img.shields.io/badge/${label}-${percentage}%25-${color}?style=plastic&logo=github"
             
            # Replace existing badge with the new one.
            escaped_badge_url=$(printf '%s\n' "$badge_url" | sed -e 's/[\/&]/\\&/g')
            # substitute|find_regexp|replace_string
            sed -i "s|\!\[${label}\].*|\!\[${label}\]\(${escaped_badge_url}\)|" README.md
          done
      - name: Commit new README
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          author_name: TestActionBot
          committer_name: ActionBot
          committer_email: no_email@no_reply.com
          message: 'Test Badges updated by Action Bot'